# Práctica 0: INTRODUCCIÓN


## Ejercicio 1
Dados los vectores $a = (4,3,8,1)$ y $b = (2,2,1,6)$:


1.   Obtener la suma de los vectores a y b.
2.   Obtener un vector c cuyos componentes sean los elementos del vector a 
multiplicados por cada elementocorrespondiente del vector b.
3.   Obtener un vector d cuyos componentes sean los elementos del vector a elevados a la potencia especificada por cada elemento correspondiente en el vector b.



In [2]:
import numpy as np
from numpy import linalg as la

a = np.array([4, 3, 8, 1])
b = np.array([2, 2, 1, 6])

# Apartado 1
c = a + b
print("Apartado 1:\n" + str(c))

# Apartado 2
c = np.zeros(4)
c = a * b
print("Apartado 2:\n" + str(c))

# Apartado 3
d = pow(a, b)
print("Apartado 3:\n" + str(d))

Apartado 1:
[6 5 9 7]
Apartado 2:
[8 6 8 6]
Apartado 3:
[16  9  8  1]


## Ejercicio 2 <font color='red'>TODO</font>
Dado $A = \begin{pmatrix} 1 & 2 & -1 \\ 1 & 0 & 1 \\ 4 & -4 & 5 \end{pmatrix}$
1.   Obtener su matriz transpuesta $A^T$.
2.   Comprobar si tiene inversa $A^{-1}$ y en caso de que la tenga, calcularla.
3.   Calcular sus valores y vectores propios.
4.   Comprobar que se cumple que, para cada valor propio $\lambda$ y vector propio asociado v, se tiene $Av = \lambda v$

In [3]:
a = np.array([[1, 2, -1], [1, 0, 1], [4, -4, 5]])

# Apartado 1
a_t = a.transpose()
print("Apartado 1:\n" + str(a_t))

# Apartado 2
a_i = la.inv(a)
print("Apartado 2:\n" + str(a_i))

# Apartado 3
eigen_vals, eigen_vect = la.eig(a) 
print("Apartado 3:\n"
          + "\t Valores propios: " + str(eigen_vals) + "\n"
          + "\t Vectores propios:\n" + str(eigen_vect))

# Apartado 4
# TODO No se cumple
print("\n########   Eigen ecuation  ########\n")
for i in range(len(eigen_vals)):
    left = np.matmul(a, eigen_vect[i])
    right = (eigen_vals[i] * eigen_vect[i])
    print(str(left) + " == " + str(right))

Apartado 1:
[[ 1  1  4]
 [ 2  0 -4]
 [-1  1  5]]
Apartado 2:
[[ 0.66666667 -1.          0.33333333]
 [-0.16666667  1.5        -0.33333333]
 [-0.66666667  2.         -0.33333333]]
Apartado 3:
	 Valores propios: [3. 2. 1.]
	 Vectores propios:
[[-0.23570226  0.43643578  0.40824829]
 [ 0.23570226 -0.21821789 -0.40824829]
 [ 0.94280904 -0.87287156 -0.81649658]]

########   Eigen ecuation  ########

[ 0.22892101  0.17254603 -0.64731071] == [-0.70710678  1.30930734  1.22474487]
[ 0.20751477 -0.17254603 -0.22556085] == [ 0.47140452 -0.43643578 -0.81649658]
[0.0135625  0.12631246 3.18023951] == [ 0.94280904 -0.87287156 -0.81649658]


## Ejercicio 3 
Construir una matriz $A$ de $2 \times 3$ elementos con números aleatorios.
1.   Construir una matriz $B$ formada por la matriz $A$ y la matriz identidad a su derecha.
2.   Construir una matriz $C$ extrayendo las columnas impares de la matriz $B$.
3.   Construir una matriz $D$ formada por la intersección de la primera fila de $B$ y sus columnas tercera y cuarta.

In [4]:
a = np.random.randint(0, 10, (2, 3))
print("Matriz A:\n" + str(a) + "\n")

# Apartado 1:
b = np.concatenate((a, np.eye(2)), axis=1)
print("Apartado 1:\n" + str(b))

# Apartado 2: sintaxis de slicing MATRIZ[i:j:k] i --> inicio
                                            #   j --> fin
                                            #   k --> paso
c = b[:, 0::2]
print("Apartado 2:\n" + str(c))

# Apartado 3:
d = np.where((b[0] == b[:,2:3]), b[0], 0)
print("Apartado 3:\n" + str(d))

Matriz A:
[[8 7 0]
 [4 0 3]]

Apartado 1:
[[8. 7. 0. 1. 0.]
 [4. 0. 3. 0. 1.]]
Apartado 2:
[[8. 0. 0.]
 [4. 3. 1.]]
Apartado 3:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Ejercicio 4
Construir una matriz a de $4 \times 4$ elementos con números aleatorios.
1.  Obtener la suma de los elementos de cada fila.
2.  Obtener la suma de los elementos de cada columna.
3.  Obtener la suma de los elementos de su diagonal principal.
4.  Extraer la submatriz cuya diagonal son los elementos $a_{1,1}$ y $a_{2,2}$.

In [5]:
a = np.random.randint(0, 10, (4, 4))
print("Matriz A:\n" + str(a))

# Apartado 1
sum_elem_filas = np.sum(a, axis=1)
print("Apartado 1:\n" + str(sum_elem_filas))

# Apartado 2
sum_elem_cols = np.sum(a, axis=0)
print("Apartado 2:\n" + str(sum_elem_cols))

# Apartado 3
traza = np.trace(a)
print("Apartado 3: " + str(traza))

# Apartado 4
sub_m = a[1:3, 1:3]
print("Apartado 4:\n" + str(sub_m))

Matriz A:
[[0 0 6 9]
 [6 9 7 3]
 [2 4 7 8]
 [6 0 4 6]]
Apartado 1:
[15 25 21 16]
Apartado 2:
[14 13 24 26]
Apartado 3: 22
Apartado 4:
[[9 7]
 [4 7]]


## Ejercicio 5

Crear las matrices $M = \begin{pmatrix} 1& 2 & 3 & 3 \\ 2 & 2 & 0 & 0 \\ 5 & 6 & 3 & 1 \\ 0 & 2 & 0 & 5 \end{pmatrix}$ y $N = \begin{pmatrix} 1& 2 & 3 & 3 \\ -1 & 2 & 0 & 0 \\ 5 & 6 & 3 & 1 \\ 0 & 2 & 0 & 4 \end{pmatrix}$

1.  Crear una matriz $O$ cuyos elementos $(i,j)$ son $o_{i,j} = 2m_{i,j} - 3n_{i,j}$
1.  Crear una matriz $O$ cuyos elementos $(i,j)$ son $p_{i,j} = \frac{1}{3}m_{i,j}^3$
1.  Crear una matriz $O$ cuyos elementos $(i,j)$ son $p_{i,j} = n_{i,j}-\frac{1+ \sqrt{5}}{2}$


In [6]:
m = np.array([[1, 2, 3, 3], [2, 2, 0, 0], [5, 6, 3, 1], [0, 2, 0, 5]])
n = np.array([[1, 2, 3, 3], [-1, 2, 0, 0], [5, 6, 3, 1], [0, 2, 0, 4]])
print("Matriz M:\n" + str(m) + "\nMatriz N:\n", str(n))

# Apartado 1
o = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        o[i, j] = (2 * m[i, j]) - (3 * n[i, j])
print("Apartado 1:\n" + str(o))

# Apartado 2
p = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        p[i, j] = (1/3) * pow(m[i, j], 3)
print("Apartado 2:\n", str(p))

# Apartado 3
q = np.zeros((4, 4))
for i in range(4):
    for j in range(4):
        q[i, j] = n[i, j] - ((1 + np.sqrt(5)) / 2)
print("Apartado 3:\n" + str(q))

Matriz M:
[[1 2 3 3]
 [2 2 0 0]
 [5 6 3 1]
 [0 2 0 5]]
Matriz N:
 [[ 1  2  3  3]
 [-1  2  0  0]
 [ 5  6  3  1]
 [ 0  2  0  4]]
Apartado 1:
[[-1. -2. -3. -3.]
 [ 7. -2.  0.  0.]
 [-5. -6. -3. -1.]
 [ 0. -2.  0. -2.]]
Apartado 2:
 [[ 0.33333333  2.66666667  9.          9.        ]
 [ 2.66666667  2.66666667  0.          0.        ]
 [41.66666667 72.          9.          0.33333333]
 [ 0.          2.66666667  0.         41.66666667]]
Apartado 3:
[[-0.61803399  0.38196601  1.38196601  1.38196601]
 [-2.61803399  0.38196601 -1.61803399 -1.61803399]
 [ 3.38196601  4.38196601  1.38196601 -0.61803399]
 [-1.61803399  0.38196601 -1.61803399  2.38196601]]


## Ejercicio 6

Teniendo en cuenta la matriz $M$ del ejercicio 5, sumar a la tercera fila la primera fila multiplicada por 3. Cambiar la primera columna de $M$ por la tercera.

In [7]:
print("Matriz M:\n" + str(m))

# Solucion
new_mat = m.copy()
new_mat[2] = m[2] + (m[0] * 3)
new_mat[:, [2, 0]] = new_mat[:, [0, 2]]
print("Solucion:\n" + str(new_mat))

Matriz M:
[[1 2 3 3]
 [2 2 0 0]
 [5 6 3 1]
 [0 2 0 5]]
Solucion:
[[ 3  2  1  3]
 [ 0  2  2  0]
 [12 12  8 10]
 [ 0  2  0  5]]


## Ejercicio 7
Tomando la matriz $N$ del ejercicio 5, hallar el valor mínimo dentro de cada fila de $N$. Ordenar los elementos de cada columna de $N$ en orden ascendente. 

In [8]:
print("Matriz N:\n" + str(n))

# Solucion
new_mat = n.copy()
min_values = np.zeros(new_mat.shape[0])
for i in range(new_mat.shape[0]):
    min_values[i] = min(new_mat[i])

min_values.sort()
print("Solucion:\n" + str(min_values))

Matriz N:
[[ 1  2  3  3]
 [-1  2  0  0]
 [ 5  6  3  1]
 [ 0  2  0  4]]
Solucion:
[-1.  0.  1.  1.]


## Ejercicio 8
Dados los vectores $a = (1,3,5,7)$ y $b = (2,4,6,8)$, construir la matriz $C = \begin{pmatrix} 2& 4 & 6 & 8 \\ 6 & 12 & 18 & 24 \\ 10 & 20 & 30 & 40 \\ 14 & 28 & 42 & 56 \end{pmatrix}$

In [9]:
a = np.array([1, 3, 5, 7])
b = np.array([2, 4, 6, 8])

# La matriz c se corresponde con
# ( b * a[0] )  
# ( b * a[1] )
# ( b * a[2] )
# ( b * a[3] )
c = np.zeros((4, 4))
for i in range(len(a)):
    c[i] = a[i] * b

print("Solucion:\n" + str(c))

Solucion:
[[ 2.  4.  6.  8.]
 [ 6. 12. 18. 24.]
 [10. 20. 30. 40.]
 [14. 28. 42. 56.]]


## Ejercicio 9
Construir una matriz de $5 \times 5$ elementos con números aleatorios. Con una sola instrucción,cambiar todos los valores de la diagonal principal a cero.

In [10]:
mat = np.random.rand(5, 5)
np.fill_diagonal(mat, 0)
print("Solucion:\n" + str(mat))

Solucion:
[[0.         0.49663033 0.2612386  0.76349641 0.67057052]
 [0.35831538 0.         0.25761045 0.86094965 0.55442792]
 [0.35024626 0.75116029 0.         0.8342381  0.96292551]
 [0.93741397 0.9197614  0.72920736 0.         0.94314965]
 [0.22076043 0.84523778 0.29479567 0.29552033 0.        ]]


## Ejercicio 10

Dada la matriz $X = \begin{pmatrix} 1&2&3&4 \\ 5&6&7&8 \\ 9&10&11&12 \\ 13&14&15&16 \end{pmatrix}$, construir la matriz $Y = \begin{pmatrix} 1&1&1&1 \\ 1&6&1&1 \\ 1&1&11&1 \\ 1&1&1&16 \end{pmatrix}$

In [11]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
y = np.ones((4, 4))
np.fill_diagonal(y, np.diagonal(x))
print("Solucion:\n" + str(y))

Solucion:
[[ 1.  1.  1.  1.]
 [ 1.  6.  1.  1.]
 [ 1.  1. 11.  1.]
 [ 1.  1.  1. 16.]]


## Ejercicio 11
Dado el vector $v = (2,4,6,8)$ y la matriz $M = \begin{pmatrix} 1&1&1&1 \\2&2&2&2 \\ 3&3&3&3 \\ 4&4&4&4 \end{pmatrix}$. Construir en una instrucción la matriz $W = \begin{pmatrix} 2&1&1&1 \\2&4&2&2 \\ 3&3&6&3 \\ 4&4&4&8 \end{pmatrix}$.


In [12]:
v = np.array([2, 4, 6, 8])
m = np.array([[1, 1, 1, 1], [2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])
np.fill_diagonal(m, v)
print("Solucion:\n" + str(m))

Solucion:
[[2 1 1 1]
 [2 4 2 2]
 [3 3 6 3]
 [4 4 4 8]]


## Ejercicio 12
Dada la matriz $X = \begin{pmatrix} 1&-2&-3&4 \\ -5&6&7&-8 \\ -9&-10&11&12 \\ 13&-14&-15&-16 \end{pmatrix}$. Poner todos los elementos negativos a 20.

In [13]:
x = np.array([[1, -2, -3, 4], [-5, 6, 7, -8], [-9, -10, 11, 12], [13, -14, -15, -16]])
sol = np.where(x > 0, x, 20)    # np.where(<condicion>, <retorno si verdadero>, <retorno si falso>)
print("Solucion:\n" + str(sol))

Solucion:
[[ 1 20 20  4]
 [20  6  7 20]
 [20 20 11 12]
 [13 20 20 20]]


## Ejercicio 13
Dada la matriz $X$ del ejercicio 12, poner todos los elementos mayores que -5 y menores que 6 a 11.

In [14]:
new_x = x.copy()
sol = np.where((x > -5) & (x < 6), 11, x)
print("Solucion:\n", sol)

Solucion:
 [[ 11  11  11  11]
 [ -5   6   7  -8]
 [ -9 -10  11  12]
 [ 13 -14 -15 -16]]


### EJERCICIOS DE POLINOMIOS

## Ejercicio 14

Dados los polinomios $p(x) = x^6 - 15x^4 + 85x^4 - 225x^3 + 274x^2 - 120x$ y
$q(x) = x^3-9x^2-26x-24$. 

1.  Representar los polinomios como ndarrays
2.  Obtener los valores $p(-2), p(-3), q(-1)$
3.  Obtener $p(x)+q(x)$
4.  Obtener $p(x)-q(x)$
5.  Obtener $p(x)+q(x)-p(x)*q(x)$
6. Obtener el resultado de dividir $p$ por $q$.

In [15]:
P = np.array([1, 0, 70, 225, 274, -120, 0])
Q = np.array([1, -9, -26, -24])

# Apartado 1
print("Polinomio p(x): " + str(P))
print("Polinomio q(x): " + str(Q))

# Apartado 2
p_minus2 = np.polyval(P, -2)
p_minus3 = np.polyval(P, -3)
q_minus1 = np.polyval(Q, -1)

print("p(-2) = " + str(p_minus2))
print("p(-1) = " + str(p_minus3))
print("q(-1) = " + str(q_minus1))

# Apartado 3
p_plus_q = np.polyadd(P, Q)
print("p(x) + q(x) = " + str(p_plus_q))

# Apartado 4
p_minus_q = np.polysub(P, Q)
print("p(x) - q(x) = " + str(p_minus_q))

# Apartado 5
op_res = np.polymul(P, Q)
op_res = np.polysub(np.polyadd(P, Q), op_res)
print("p(x) + q(x) - p(x) * q(x) = " + str(op_res))

# Apartado 6
div = np.polydiv(P, Q)
print("p(x) / q(x) = " + str(div))

Polinomio p(x): [   1    0   70  225  274 -120    0]
Polinomio q(x): [  1  -9 -26 -24]
p(-2) = 720
p(-1) = 3150
q(-1) = -8
p(x) + q(x) = [   1    0   70  226  265 -146  -24]
p(x) - q(x) = [  1   0  70 224 283 -94  24]
p(x) + q(x) - p(x) * q(x) = [   -1     9   -44   430  3571 10186 11670  3721 -3026   -24]
p(x) / q(x) = (array([1.000e+00, 9.000e+00, 1.770e+02, 2.076e+03]), array([23776., 58104., 49824.]))


## Ejercicio 15 <font color='red'>TODO</font>

Dado el polionomio $r(x) = (x-2)^2 (x+3)(x-7)$
1.  Dar la expresión de $r$ de forma simbólica
2. Pasar la expresión simbólica a numérica
3.  Obtener el resultado de dividir $r$ por $s(x) = x^2 -4x-21$
4.  Obtener la expresión simbólica del polinomio resultante del apartado anterior.


In [16]:
# Apartado 1
# TODO

# Apartado 2
r = np.poly([2, -3 , 7])
print("Forma numerica: " + str(r))

# Apartado 3
s = np.array([1, -4, -21])
res = np.polydiv(r, s)
print("r(x) / s(x) = " + str(res))

# Apartado 4
# TODO

Forma numerica: [  1.  -6. -13.  42.]
r(x) / s(x) = (array([ 1., -2.]), array([0.]))


## Ejercicio 16 <font color='red'>TODO</font>
Halla el mínimo absoluto del polinomio $p(x) = x^2 + x + 1$.


In [18]:

# Para hallar el mínimo absoluto tenemos que encontrar el minimo de entre estos valores:
#   - El menor valor f(x) para todos los puntos donde f'(x) = 0.
#   - El menor valor f(x) donde f no es derivable.
#   - EL menor valor de f en los limites del intervalo.
p = np.array([1, 1, 1])
der = np.polyder(p)

TypeError: 'numpy.ndarray' object is not callable