# **PRÁCTICA 4:** Resolución aproximada de ecuaciones mediante los métodos de Horner y Sturm

## 1. Método de Horner

Implementar el Método de Horner para que, dado un polinomio $P(x)$ de
cualquier grado y un punto $x_0 \in \mathbb{R}$, se determine otro polinomio $Q(x)$ tal que

$$ P(x) = (x-x_0) \: Q(x) + P(x_0) $$

In [86]:
import numpy as np

In [87]:
def Horner(P,x_0):
    res = np.zeros([len(P)])
    res[0] = P[0]
    for i in range(1, len(P)):
        res[i] = (res[i - 1] * x_0) + P[i]
    Q = res[0:(len(P) - 1)]
    resto = res[-1]
    return Q, resto

Utilizarla en:

$$P(x) = 5x^3+7x^2+2x+3$$ 
con 
$x_0=0$ y $x_0 = 3$

In [88]:
P = np.array([5, 7, 2, 3])
Q, resto = Horner(P, 0)
print(f'Polinomio: {Q}, resto: {resto}')

Polinomio: [5. 7. 2.], resto: 3.0


## 2. Método de Sturm

1. Implementar el Método de Sturm para, dado un polinomio $P(x)$, **construir la secuencia de polinomios de Sturm**. Hacer una función que devuelva una lista de polinomios (ndarrays).

In [89]:
def SturmSequence(P):
    S = list()
    S.append(P) # Primer polinomio de sturm, el propio polinomio
    S.append(np.polyder(P)) # Segundo polinomio de sturm, la derivada del polinomio
    _, resto = np.polydiv(S[0], S[1]) # Tercer polinomio de sturm
    S.append(resto)
    cont = 2
    while len(resto) > 1:
        _, resto = np.polydiv(S[cont - 1], S[cont]) # Sucesivos polinomios de la secuencia 
                                                    # hasta tener unicamente un termino independiente
        S.append(resto)
        cont += 1
    return S

In [90]:
seq = SturmSequence(P)
seq

[array([5, 7, 2, 3]),
 array([15, 14,  2]),
 array([-0.84444444,  2.68888889]),
 array([198.66689751])]

2. Complementar la implementación del apartado 1, para, utilizando el Método de Sturm, **hallar el número de raíces positivas y negativas** de $P(x)$ en un intervalo dado. Hacer una función que devuelva los valores `pos` y `neg`.

NOTA: Asumir que todas las raíces son simples. 

In [91]:
def numberOfRoots(P, interval):
    sequence = SturmSequence(P)
    sign_changes = [np.sign(np.polyval(p, interval[0])) != np.sign(np.polyval(p, interval[1])) for p in sequence]
    return np.sum(sign_changes[:-1]) - np.sum(sign_changes[1:])

In [92]:
neg = numberOfRoots(P, interval = [-10, 0])
pos = numberOfRoots(P, interval = [0, 10])
(pos, neg)

(0, 1)

3. Utilizar la implementación del apartado 2 para **separar las raíces de un
polinomio** dado (es decir, encontrar intervalos que contengan una y solamente
una raíz). Hacer una función que devuelva una lista de intervalos.

NOTA: Asumir que todas las raíces del polinomio son reales y simples.


In [93]:
def SturmIntervals(P):
  intervals = list()
  test = [-10, 10]
  neg = numberOfRoots(P, [test[0], 0])
  pos = numberOfRoots(P, [0, test[1]])

  if (neg == 1):
    intervals.append([test[0], 0])

  if (pos == 1):
    intervals.append([0, test[1]])

  while (neg > 1) and (pos > 1):
    print(test)
    if (neg > 1):
      test = [test[0], (test[1] - test[0]) / 2]
      neg = numberOfRoots(P, test)
    
    if (pos > 1):
      test = [(test[1] - test[0]) / 2, test[1]]
      pos = numberOfRoots(P, test)

    if (neg == 1):
      intervals.append([test[0], test[1]])

    if (pos == 1):
      intervals.append([test[0], test[1]])
    
  return intervals


In [94]:
intervals = SturmIntervals(P)
intervals

[[-10, 0]]

Calcular los intervalos de separación de las raíces de los siguientes polinomios:

$$P_1(x) = x^3-9x^2+24x-36$$
$$P_2(x) = x^6 - 9.5x^5 + 18x^4 + 33.5x^3 - 97x^2 + 18x +36$$

In [95]:
P_1 = np.array([1, -9, 24, -36])
P_2 = np.array([1, -9.5, 18, 33.5, -97, 18, 36])

i = SturmIntervals(P_1)
i2 = SturmIntervals(P_2)
p1n = numberOfRoots(P_1, interval=[-10, 0])
p1p = numberOfRoots(P_1, interval=[0, 10])
p2n = numberOfRoots(P_2, interval=[-10, 0])
p2p = numberOfRoots(P_2, interval=[0, 10])

print((p1n, p1p))
print((p2n, p2p))

print(i)
print(i2)

(0, 1)
(0, 0)
[[0, 10]]
[]
