# **PRÁCTICA 4:** Resolución aproximada de ecuaciones mediante los métodos de Horner y Sturm

## 1. Método de Horner

Implementar el Método de Horner para que, dado un polinomio $P(x)$ de
cualquier grado y un punto $x_0 \in \mathbb{R}$, se determine otro polinomio $Q(x)$ tal que

$$ P(x) = (x-x_0) \: Q(x) + P(x_0) $$

In [4]:
import numpy as np

In [5]:
def Horner(P,x_0):
    res = np.zeros([len(P)])
    res[0] = P[0]
    for i in range(1, len(P)):
        res[i] = (res[i - 1] * x_0) + P[i]
    Q = res[0:(len(P) - 1)]
    resto = res[-1]
    return Q, resto

Utilizarla en:

$$ P(x) = 5x^3+7x^2+2x+3$$ con $x_0=0$ y $x_0 = 3$

In [6]:
P = np.array([5, 7, 2, 3])
Q, resto = Horner(P, 3)
print(f'Polinomio: {Q}, resto: {resto}')

Polinomio: [ 5. 22. 68.], resto: 207.0


## 2. Método de Sturm

1. Implementar el Método de Sturm para, dado un polinomio $P(x)$, **construir la secuencia de polinomios de Sturm**. Hacer una función que devuelva una lista de polinomios (ndarrays).

In [7]:
def SturmSequence(P):
    S = list()
    S.append(P) # Primer polinomio de sturm, el propio polinomio
    S.append(np.polyder(P)) # Segundo polinomio de sturm, la derivada del polinomio
    _, resto = np.polydiv(S[0], S[1]) # Tercer polinomio de sturm
    S.append(resto)
    cont = 2
    while len(resto) > 1:
        _, resto = np.polydiv(S[cont - 1], S[cont]) # Sucesivos polinomios de la secuencia 
                                                    # hasta tener unicamente un termino independiente
        S.append(resto)
        cont += 1
    return S

In [8]:
seq = SturmSequence(P)
seq

[array([5, 7, 2, 3]),
 array([15, 14,  2]),
 array([-0.84444444,  2.68888889]),
 array([198.66689751])]

2. Complementar la implementación del apartado 1, para, utilizando el Método de Sturm, **hallar el número de raíces positivas y negativas** de $P(x)$ en un intervalo dado. Hacer una función que devuelva los valores `pos` y `neg`.

NOTA: Asumir que todas las raíces son simples. 

In [14]:
def numberOfRoots(P):
    interval = [-10, 10]
    seq = SturmSequence(P)
    pos_c = 0
    neg_c = 0
    zero_c = 0
    val_n_ant = np.polyval(seq[0], interval[0])
    val_0_ant = np.polyval(seq[0], 0)
    val_p_ant = np.polyval(seq[0], interval[1])
    
    for elem in seq:
        val_n = np.polyval(elem, interval[0])
        val_0 = np.polyval(elem, 0)
        val_p = np.polyval(elem, interval[1])
        
        if (val_n_ant * val_n < 0):
            neg_c += 1
        if (val_p_ant * val_p < 0):
            pos_c += 1
        if (val_0_ant * val_0 < 0):
            zero_c += 1
        
        val_n_ant = val_n
        val_0_ant = val_0
        val_p_ant = val_p
        
    neg = neg_c - zero_c 
    pos = zero_c - pos_c
    print(f"cambios neg {neg_c} cambios pos {pos_c} cambios cero {zero_c}")
        
    return pos, neg ## TODO devolver neg y pos o neg_c y pos_c

In [15]:
pos, neg = numberOfRoots(P)
(pos, neg)

cambios neg 1 cambios pos 2 cambios cero 0


(-2, 1)

3. Utilizar la implementación del apartado 2 para **separar las raíces de un
polinomio** dado (es decir, encontrar intervalos que contengan una y solamente
una raíz). Hacer una función que devuelva una lista de intervalos.

NOTA: Asumir que todas las raíces del polinomio son reales y simples.


In [11]:
def SturmIntervals(P):
  pass
  #return intervals

In [12]:
intervals = SturmIntervals(P)
intervals

Calcular los intervalos de separación de las raíces de los siguientes polinomios:

$$P_1(x) = x^3-9x^2+24x-36$$
$$P_2(x) = x^6 - 9.5x^5 + 18x^4 + 33.5x^3 - 97x^2 + 18x +36$$